// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0RhVlAiipW_glOIdLDOzCZppNNzLHgpI',
    appId: '1:899305284022:web:675baf560970e06ae12117',
    messagingSenderId: '899305284022',
    projectId: 'cazzcar-1374e',
    authDomain: 'cazzcar-1374e.firebaseapp.com',
    storageBucket: 'cazzcar-1374e.firebasestorage.app',
    measurementId: 'G-THZLPEMN03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu__7ERnkD4rbOe33F4W52cMlIMyupldE',
    appId: '1:899305284022:android:c908a8d0b84f2089e12117',
    messagingSenderId: '899305284022',
    projectId: 'cazzcar-1374e',
    storageBucket: 'cazzcar-1374e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAztjh756WPRWVjmIWMzxQ_A-PkCTC3vkE',
    appId: '1:899305284022:ios:6bb21ca242e71454e12117',
    messagingSenderId: '899305284022',
    projectId: 'cazzcar-1374e',
    storageBucket: 'cazzcar-1374e.firebasestorage.app',
    iosBundleId: 'com.example.cazzcar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAztjh756WPRWVjmIWMzxQ_A-PkCTC3vkE',
    appId: '1:899305284022:ios:6bb21ca242e71454e12117',
    messagingSenderId: '899305284022',
    projectId: 'cazzcar-1374e',
    storageBucket: 'cazzcar-1374e.firebasestorage.app',
    iosBundleId: 'com.example.cazzcar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0RhVlAiipW_glOIdLDOzCZppNNzLHgpI',
    appId: '1:899305284022:web:77ce505db4541bd2e12117',
    messagingSenderId: '899305284022',
    projectId: 'cazzcar-1374e',
    authDomain: 'cazzcar-1374e.firebaseapp.com',
    storageBucket: 'cazzcar-1374e.firebasestorage.app',
    measurementId: 'G-L6D8LQ9N6D',
  );
}
